#! /bin/bash

PRGNAME="ninja"

### Ninja (build system with a focus on speed)
# небольшая система сборки, ориентированная на скорость

ROOT="/"
source "${ROOT}check_environment.sh"                  || exit 1
source "${ROOT}unpack_source_archive.sh" "${PRGNAME}" || exit 1

TMP_DIR="/tmp/pkg-${PRGNAME}-${VERSION}"
rm -rf "${TMP_DIR}"
BASH_COMPL="share/bash-completion/completions"
ZSH_COMPL="share/zsh/site-functions"
mkdir -pv "${TMP_DIR}/usr"/{bin,"${BASH_COMPL}","${ZSH_COMPL}"}

# при запуске ninja обычно запускает максимальное количество процессов
# параллельно. По умолчанию это количество ядер в системе + 2. В некоторых
# случаях это может перегреть процессор или привести к нехватке памяти в
# системе. Если запустить из командной строки с параметром -jN, где N - число
# потоков, то можно ограничить количество параллельных процессов, но некоторые
# пакеты при сборке не передают параметр -jN. Можно установить переменную
# окружения NINJAJOBS, для принудительного ограничения количества потоков
# сборки, например:
#    # export NINJAJOBS="-j4"

# добавим возможность использовать переменную окружения NINJAJOBS
sed -i "/int Guess/a \\
  char* jobs = getenv( \"NINJAJOBS\" );\\
\\
  if ( jobs != NULL ) {\\
    int j = 0;\\
    int lenJobsEnv = strlen(jobs);\\
\\
    if (lenJobsEnv > 1) {\\
      j = jobs[lenJobsEnv - 1] - '0';\\
    } else {\\
      j = atoi(jobs);\\
    }\\
\\
    if (j > 0) return j;\\
  }\\
\\
  int countProcs = GetProcessorCount();\\
  return countProcs;\\
" src/ninja.cc || exit 1

# заставляет ninja пересобрать себя под текущую систему
#    --bootstrap
python3 configure.py \
    --bootstrap || exit 1

# тесты не могут выполняться в среде chroot, а также требуется cmake

# устанавливаем пакет
install -vm755  "${PRGNAME}"         "${TMP_DIR}/usr/bin/"
install -vDm644 misc/bash-completion "${TMP_DIR}/usr/${BASH_COMPL}/${PRGNAME}"
install -vDm644 misc/zsh-completion  "${TMP_DIR}/usr/${ZSH_COMPL}/_${PRGNAME}"

source "${ROOT}/stripping.sh"      || exit 1
source "${ROOT}/update-info-db.sh" || exit 1
/bin/cp -vR "${TMP_DIR}"/* /

cat << EOF > "/var/log/packages/${PRGNAME}-${VERSION}"
# Package: ${PRGNAME} (build system with a focus on speed)
#
# Ninja is a small build system with a focus on speed. It differs from other
# build systems in two major respects: it is designed to have its input files
# generated by a higher-level build system, and it is designed to run builds as
# fast as possible.
#
# Home page: https://${PRGNAME}-build.org/
# Download:  https://github.com/${PRGNAME}-build/${PRGNAME}/archive/v${VERSION}/${PRGNAME}-${VERSION}.tar.gz
#
EOF

source "${ROOT}write_to_var_log_packages.sh" \
    "${TMP_DIR}" "${PRGNAME}-${VERSION}"
