#! /bin/bash

# Written for Linux From Scratch by MyRequiem <mrvladislavovich@gmail.com>

# Properly uninstalls the specified package from the system. The utility
# analyzes the installation log in /var/log/packages/, removes all associated
# files and empty directories, and updates the system's installed software
# database.
#
# Prevents "orphaned" files and maintains filesystem integrity after package
# removal.

if test "${EUID}" -ne 0; then
    echo "$(basename "$0") must be run as the root user! "
    exit 1
fi

PACKAGES_DIR="/var/log/packages"
REMOVED_PACKAGES_DIR="/var/log/removed_packages"
PRESERVED_DIR="/var/log/setup/tmp/preserved"
DATE_TIME="$(date "+%d.%m.%y_%H:%M:%S")"

usage() {
cat << EOF

Usage: removepkg [params] [/var/log/packages/]pkgname-version

### NOTE:
    Packages that can only be updated and copied, but cannot be completely
    remove from the system:
        main-directory-tree
        syshealth-utils
        lfs-bootscripts
        network-configuration
        system-v-configuration
        etc-profile
        etc-fstab
        glibc
        binutils
        gcc
        kernel-headers
        zlib
        xz
        zstd
        readline

Parameters:
  --fake        Dry run: generate a report to standard output of files
                and directories that would be removed without actually
                deleting the package.

  --backup      Reconstruct the complete package subtree in
                /var/log/setup/tmp/preserved/pkgname-version
                before removing the package from the system.

  --copy        Reconstruct the complete package subtree in
                /var/log/setup/tmp/preserved/pkgname-version
                without removing the package from the system.

  --no-color    Disable colorized output.

EOF
}

confirm_continuation() {
    echo -en "${LGREEN}Continue?${COLORRESET} [y/N]: "
    read -r JUNK
    [[ "${JUNK}" != "y" && "${JUNK}" != "Y" ]] && exit 1
    echo ""
}

backup() {
    ITEM="$1"

    if  [[ -L "${ITEM}" || -f "${ITEM}" ]]; then
        DIRNAME="${PRESERVED_DIR}/${PKG}_${DATE_TIME}$(dirname "${ITEM}")"
        if ! [ -d "${DIRNAME}" ]; then
            echo -en "${MAGENTA}Creating directory "
            echo -e "${BROWN}${DIRNAME}${COLORRESET}"
            mkdir -p "${DIRNAME}"
        fi
    fi

    if [ -L "${ITEM}" ]; then
        LINKNAME="$(basename "${ITEM}")"
        TARGET="$(readlink "${ITEM}")"
        echo -en "${GRAY}Creating symbolic link "
        echo -en "${LCYAN}${LINKNAME}${COLORRESET} -> ${CYAN}${TARGET}${GREEN} "
        echo -e "in ${BROWN}${DIRNAME}/${COLORRESET}"
        (
            cd "${DIRNAME}" || exit 1
            ln -sf "${TARGET}" "${LINKNAME}"
        )
    elif [ -d "${ITEM}" ]; then
        if ! [ -d "${PRESERVED_DIR}/${PKG}_${DATE_TIME}${ITEM}" ]; then
            echo -en "${MAGENTA}Creating directory "
            echo -e "${BROWN}${PRESERVED_DIR}/${PKG}_${DATE_TIME}${ITEM}${COLORRESET}"
            mkdir -p "${PRESERVED_DIR}/${PKG}_${DATE_TIME}${ITEM}"
        fi
    else
        echo -en "${GREEN}Copy ${CYAN}${LINE}${GREEN} to "
        echo -e "${BROWN}${DIRNAME}/${COLORRESET}"
        cp "${ITEM}" "${DIRNAME}/"
    fi
}

remove_package() {
# when removing files, removepkg analyzes other installed packages and deletes
# only those files unique to the package being removed
    if [ -n "${BACKUP}" ]; then
        {
            while read -r LINE; do
                # skip comments
                if ! [[ "${LINE}" =~ ^# ]]; then
                    backup "${LINE}"
                fi
            done
        } < "${PACKAGES_DIR}/${PKG}"

        mkdir -p "${PRESERVED_DIR}/${PKG}_${DATE_TIME}/var/log/packages"
        cp "/var/log/packages/${PKG}" \
            "${PRESERVED_DIR}/${PKG}_${DATE_TIME}/var/log/packages/"

        if [ -n "${FAKE}" ]; then
            exit 0
        fi
    fi

    # removing files
    {
        while read -r LINE; do
            if [ -L "${LINE}" ]; then
                TYPE=" ${LCYAN}[L]${COLORRESET}"
            elif [ -f "${LINE}" ]; then
                TYPE=" ${GREEN}[F]${COLORRESET}"
            fi

            echo -e "${MAGENTA}Removing${COLORRESET}${TYPE} ${LINE}"
            # real removal
            if [ -z "${FAKE}" ]; then
                rm -f "${LINE}" &>/dev/null
            fi
        done
    } < "${FILES_TO_DELETE}"

    # removing directories
    {
        while read -r LINE; do
            # real removal
            if [ -z "${FAKE}" ]; then
                # if directory is empty
                # shellcheck disable=SC2012
                if [ "$(ls -a "${LINE}" | wc -l)" ==  "2" ]; then
                    echo -en "${MAGENTA}Removing ${BROWN}[D]${COLORRESET} "
                    echo "${LINE}"
                        rm -rf "${LINE}" &>/dev/null
                fi
            else
                echo -en "${MAGENTA}Removing if empty "
                echo -e "${BROWN}[D]${COLORRESET} ${LINE}"
            fi
        done
    } < "${DIRS_TO_DELETE}_sort"

    # show files contained in other packages that were not deleted
    {
        NOT_DELETED_FILES=""
        while read -r LINE; do
            if [[ "${LINE}" =~ ^# ]]; then
                continue
            fi

            if [[ -L "${LINE}" || -f "${LINE}" ]]; then
                if ! grep -qE "^${LINE}$" "${FILES_TO_DELETE}"; then
                    NOT_DELETED_FILES="${NOT_DELETED_FILES}${LINE}\n"
                fi
            fi
        done

        if [ -n "${NOT_DELETED_FILES}" ]; then
            echo -en "\n${LRED}Files contained in other packages that "
            echo -e "have not been deleted${COLORRESET}:"
            echo -e "${NOT_DELETED_FILES}"
        fi
    } < "${PACKAGES_DIR}/${PKG}"

    # removing temporary files
    rm -f "${FILES_TO_DELETE}" "${DIRS_TO_DELETE}"{,_sort}

    # if real removal, move file from /var/log/packages/ to
    # /var/log/removed_packages/
    if [ -z "${FAKE}" ]; then
        if ! [ -d "${REMOVED_PACKAGES_DIR}" ]; then
            mkdir -p "${REMOVED_PACKAGES_DIR}"
        fi

        mv "${PACKAGES_DIR}/${PKG}" "${REMOVED_PACKAGES_DIR}/${PKG}_${DATE_TIME}"
    fi
}

NO_COLOR=""
FAKE=""
BACKUP=""
while : ; do
    case "$1" in
        --no-color)
            NO_COLOR="true";
            shift
            ;;
        --copy)
            FAKE="true";
            BACKUP="true";
            shift
            ;;
        --backup)
            BACKUP="true";
            shift
            ;;
        --fake)
            FAKE="true";
            shift
            ;;
        -*)
            usage
            exit 1
            ;;
        *) break
    esac
done

PKG=$(basename "$1")
if [ -z "${PKG}" ]; then
    usage
    exit 1
fi

if [ -z "${NO_COLOR}" ]; then
    LRED="\033[1;31m"
    LBLUE="\033[1;34m"
    GREEN="\033[0;32m"
    LGREEN="\033[1;32m"
    BROWN="\033[0;33m"
    MAGENTA="\033[0;35m"
    CYAN="\033[0;36m"
    LCYAN="\033[1;36m"
    GRAY="\033[0;37m"
    COLORRESET="\033[0;0m"
fi

if ! [ -f "${PACKAGES_DIR}/${PKG}" ]; then
    echo -en "${LRED}Package ${BROWN}${PKG}${LRED} not found in "
    echo -e "${LBLUE}${PACKAGES_DIR}/${COLORRESET}"
    exit 1
fi

STRICT_PKGS="\
main-directory-tree \
syshealth-utils \
lfs-bootscripts \
network-configuration \
system-v-configuration \
etc-profile \
etc-fstab \
glibc \
binutils \
gcc \
kernel-headers \
zlib \
xz \
zstd \
readline"
for STRICT_PKG in ${STRICT_PKGS} ; do
    [[ "${FAKE}" == "true" ]] &&  break

    if [[ ${PKG} == "${STRICT_PKG}" ]]; then
        STRICT_PKG_NAME="${PKG}"
    else
        STRICT_PKG_NAME="$(echo "${PKG}" | rev | cut -d / -f 1 | \
            cut -d - -f 2- | rev)"
    fi

    if [[ "${STRICT_PKG_NAME}" == "${STRICT_PKG}" ]]; then
        echo -en "${LRED}Package ${BROWN}${STRICT_PKG_NAME}${LRED} "
        echo -e "cannot be deleted!${COLORRESET}"
        exit 0
    fi
done

if [ "${FAKE}" = "true" ]; then
    if [ "${BACKUP}" = "true" ]; then
        echo -en "${MAGENTA}Contents of package ${LBLUE}${PKG}${MAGENTA} "
        echo -e "will be copied to"
        echo -e "${BROWN}${PRESERVED_DIR}/${PKG}/${COLORRESET}"
        confirm_continuation
    else
        echo -en "${MAGENTA}Not actually removing any files. Here's what "
        echo -en "${MAGENTA}would be\nremoved (and left behind) if you "
        echo -e "removed the package${COLORRESET}"
        confirm_continuation
    fi
else
    if [ "${BACKUP}" = "true" ]; then
        echo -en "${MAGENTA}Contents of package ${LBLUE}${PKG}${MAGENTA} "
        echo "will be copied to directory"
        echo -e "${BROWN}${PRESERVED_DIR}/${PKG}/${MAGENTA}"
        echo -e "and then package will be deleted from you system${COLORRESET}"
        confirm_continuation
    fi
fi

if [[ -z "${FAKE}" && -z "${BACKUP}" ]]; then
        echo -en "${MAGENTA}Package ${LBLUE}${PKG}${MAGENTA} will be "
        echo -e "deleted from you system${COLORRESET}"
        confirm_continuation
fi

# when removing files, removepkg analyzes other installed packages and deletes
# only those files unique to the package being removed
FILES_TO_DELETE="/tmp/removepkg_files_to_delete"
DIRS_TO_DELETE="/tmp/removepkg_dirs_to_delete"
rm -f "${FILES_TO_DELETE}"
rm -f "${DIRS_TO_DELETE}"
:> "${FILES_TO_DELETE}"
:> "${DIRS_TO_DELETE}"

echo "Building a list of files to delete. Please wait ..."
{
    while read -r LINE; do
        if [[ "${LINE}" =~ ^# ]]; then
            continue
        fi

        if ! grep -qE "^${LINE}$" --exclude="${PACKAGES_DIR}/${PKG}" \
                "${PACKAGES_DIR}"/*; then
            # if this is a directory
            if ! [[ -L "${LINE}" || -f "${LINE}" ]]; then
                if [ -e "${LINE}" ]; then
                    echo "${LINE}" >> "${DIRS_TO_DELETE}"
                fi
            else
                echo "${LINE}" >> "${FILES_TO_DELETE}"
            fi
        fi
    done
} < "${PACKAGES_DIR}/${PKG}"

sort -r "${DIRS_TO_DELETE}" > "${DIRS_TO_DELETE}_sort"

remove_package
