#! /bin/bash

CACHE_DIR="${HOME}/.cache/clipmenu"
! [ -d "${CACHE_DIR}" ] && exit

find "${CACHE_DIR}" -type f  ! \( -name "lock" -o -name "line_cache" \) \
    -exec rm {} \;

cat /dev/null > "${CACHE_DIR}/line_cache"
